apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      # Aqui define que todos os pods que esse ReplicaSet irá gerenciar terão um label app=mypod
      app: mypod

  # Aqui será a definição da estrutura de um Pod que um ReplicaSet irá gerenciar -> template
  template:
    metadata:
      labels:
        app: mypod
    spec:
    # Aqui será definida a estrutura de um container de um pod que será executado
      containers:
        - name: app-web
          image: fabricioveronez/web-page:blue
          ports: 
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mydeployment-service
spec:

  # Aqui aponta qual o label que está definido nos pods
  selector:
    app: mypod

  ports:
  - protocol: TCP
    port: 80
    name: http
    nodePort: 30000
  type: NodePort